### PR TITLE
Changes for SpringBoot

### PR DESCRIPTION
**Pull request by string01**
Mods for Springboot.
Also slf4j/logback (for nice exception stack formatting)
(not sure why it is showing 56 changed files on this PR - I might have messed up something as I have a 2 remotes (this one, and one local to our corp. git repo.)
Let me know if I need to change anything.
Thanks,
-d

### CODE REVIEW

**Comment by BaldyLocks** [comment]
Thank you for the effort. But there is something wrong with the PR (hence 56 changes). I think you accidentally committed some "work in progress" that contains the original sample project and then your changes as a subdirectory in it with some renamed files (e.g. pom.xml.orig) and even the target dir.
I mean i can fix it but not accept the PR as it is, and I would rather that it's seen as your contribution if you want to do it.

**Comment by string01** [comment]
That's what I was afraid of.
Too many things coming at once.
I'll fix it and re-submit soon.
Thx,
-d

**Comment by kaqqao** [comment]
Great! Thanks! I've been looking into moving this sample to Spring Boot for a while now.

**Comment by string01** [comment]
Closing this one and will re-open ASAP with a correct effort.

**Pull request closed without merging**
